apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-170289661
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-170289661
    app.kubernetes.io/part-of: test-app-170289661
  name: go-170289661
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-170289661
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-170289661
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/ea0ljne5-tenant/test-app-170289661/go-170289661@sha256:cc540f5a9d8394fcaf35e88c2e31d401529e057a232c89d18de530cb1b9cd460
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
